behaviors:
  Dino:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4
      buffer_size: 64
      learning_rate: 0.0003
      learning_rate_schedule: linear
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    max_steps: 2500000
    time_horizon: 25
    summary_freq: 1
    keep_checkpoints: 5
    checkpoint_interval: 500000
    threaded: true
    network_settings:
      vis_encoder_type: simple
      normalize: true
      hidden_units: 32
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
env_settings:
  env_path: C:\Users\marke\Builds\Dino\Dino
engine_settings:
  time_scale: 1
  target_frame_rate: -1
  capture_frame_rate: 0
checkpoint_settings:
  run_id: dino-debug
  resume: true
debug: true
torch_settings:
  device: cuda
environment_parameters:
  decision_period: 50
  environments_per_unity_process: 1
  multi_scene: 0
